import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js CodeWitHamida",
    template: "%s | Hamida",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "gray" }}>
          <p>this is header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "gray" }}>
          <p>this is footer</p>
        </footer>
      </body>
    </html>
  );
}
